server:
  port: 9002
spring:
  application:
    name: product-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: ""  # Keep the password empty for security reasons
