server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/NicolasMoralesDev/InventarioSystem.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}

